### ISSUE TITLE
Migrate from RecyclerViewAdapter to ListAdapter

### ISSUE THREAD

**Issue by MamboBryan** [kanake10/Cocktails#4]
Migrate the following class from recycleview adapter to list adapter.
![Screenshot from 2022-06-06 13-36-16](https://user-images.githubusercontent.com/40160345/172145180-533ed05a-bf95-4de8-9e28-a2039684c260.png) 

Resources:
https://developer.android.com/reference/kotlin/androidx/recyclerview/widget/ListAdapter

**Comment by kanake10** [comment]
solved by @mawindavic #4
